version: '3.8'

services:
  api:
    image: node-api
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_USER=sys_webapp
      - DB_PASSWORD=webappPassword
      - DB_NAME=webapp
      - PORT=3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  front-nginx:
    image: node-frontend-nginx
    volumes:
      - ./nginx-node.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.7
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: sys_webapp
      MYSQL_PASSWORD: webappPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay

volumes:
  mysql-data:
