version: '3.8'

services:
  api-2:
    image: node-api-2
    networks:
      - app-network-2
    environment:
      - DB_HOST=mysql-2
      - DB_USER=sys_webapp
      - DB_PASSWORD=webappPassword
      - DB_NAME=webapp
      - PORT=3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  front-nginx-2:
    image: node-frontend-nginx-2
    volumes:
      - ./nginx-node.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:82"
    networks:
      - app-network-2
    depends_on:
      - api  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql-2:
    image: mysql:5.7
    networks:
      - app-network-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: sys_webapp
      MYSQL_PASSWORD: webappPassword
    ports:
      - "3302:3306"
    volumes:
      - mysql-data-2:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network-2:
    driver: overlay

volumes:
  mysql-data-2:
