name: Deploy Docker Monitor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Script
        run: |
          bash ./docker-swarm-deploy.sh
