name: Deploy Docker Monitor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure Swarm active
        run: |
          SWARM_STATUS=$(docker info --format '{{.Swarm.LocalNodeState}}')
          echo "Current Swarm status: $SWARM_STATUS"
          if [ "$SWARM_STATUS" != "active" ]; then
            docker swarm init
          fi

      - name: Build Docker image
        run: |
          bash ./docker-swarm-deploy.sh
